### ISSUE TITLE
command() doesn't seem to work

### ISSUE THREAD

**Issue by gapan** [UCY-LINC-LAB/fogify#7]
I'm trying to run `command()`, but no matter what I do it doesn't seem to work. I get an `OK` message, but the command I specified, never really runs on any of the containers. For example, I'm trying to run a `touch /testfile` command, I get an `OK` response, but the file never appears in any of the running containers.

**Comment by OmarMaadarani** [comment]
Has anyone found a way to resolve this? I tracked the issue down to the `command()` method in `controller/views.py` where it says 

```
 INFO:werkzeug: 10.0.1.31 - - [10/Jan/2024 22:19:52] "POST /actions/command/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/code/fogify/controller/views.py", line 248, in post
    if action_type == "command": commands["command"] = self.command(params)
  File "/code/fogify/controller/views.py", line 219, in command
    commands = {"command": CommandAction(**params['action']).get_command()}
KeyError: 'action'
```

Any help?
